CONVERT_PATTERN_1 = \
    [["いぇ", "ye "],
     ["うぁ", "wha "],
     ["うぃ", "whi "],
     ["うぇ", "whe "],
     ["うぉ", "who "],
     ["きゃ", "kya "],
     ["きぃ", "kyi "],
     ["きゅ", "kyu "],
     ["きぇ", "kye "],
     ["きょ", "kyo "],
     ["くゃ", "qya "],
     ["くゅ", "qyu "],
     ["くょ", "qyo "],
     ["くぁ", "qwa "],
     ["くぃ", "qwi "],
     ["くぅ", "qwu "],
     ["くぇ", "qwe "],
     ["くぉ", "qwo "],
     ["ぎゃ", "gya "],
     ["ぎぃ", "gyi "],
     ["ぎゅ", "gyu "],
     ["ぎぇ", "gye "],
     ["ぎょ", "gyo "],
     ["ぐぁ", "gwa "],
     ["ぐぃ", "gwi "],
     ["ぐぅ", "gwu "],
     ["ぐぇ", "gwe "],
     ["ぐぉ", "gwo "],
     ["しゃ", "sya "],
     ["しぃ", "syi "],
     ["しゅ", "syu "],
     ["しぇ", "sye "],
     ["しょ", "syo "],
     ["すぁ", "swa "],
     ["すぃ", "swi "],
     ["すぅ", "swu "],
     ["すぇ", "swe "],
     ["すぉ", "swo "],
     ["じゃ", "zya "],
     ["じぃ", "zyi "],
     ["じゅ", "zyu "],
     ["じぇ", "zye "],
     ["じょ", "zyo "],
     ["ちゃ", "tya "],
     ["ちぃ", "tyi "],
     ["ちゅ", "tyu "],
     ["ちぇ", "tye "],
     ["ちょ", "tyo "],
     ["つぁ", "tsa "],
     ["つぃ", "tsi "],
     ["つぇ", "tse "],
     ["つぉ", "tso "],
     ["てゃ", "tha "],
     ["てぃ", "thi "],
     ["てゅ", "thu "],
     ["てぇ", "the "],
     ["てょ", "tho "],
     ["とぁ", "twa "],
     ["とぃ", "twi "],
     ["とぅ", "twu "],
     ["とぇ", "twe "],
     ["とぉ", "two "],
     ["ぢゃ", "dya "],
     ["ぢぃ", "dyi "],
     ["ぢゅ", "dyu "],
     ["ぢぇ", "dye "],
     ["ぢょ", "dyo "],
     ["でゃ", "dha "],
     ["でぃ", "dhi "],
     ["でゅ", "dhu "],
     ["でぇ", "dhe "],
     ["でょ", "dho "],
     ["どぁ", "dwa "],
     ["どぃ", "dwi "],
     ["どぅ", "dwu "],
     ["どぇ", "dwe "],
     ["どぉ", "dwo "],
     ["にゃ", "nya "],
     ["にぃ", "nyi "],
     ["にゅ", "nyu "],
     ["にぇ", "nye "],
     ["にょ", "nyo "],
     ["ひゃ", "hya "],
     ["ひぃ", "hyi "],
     ["ひゅ", "hyu "],
     ["ひぇ", "hye "],
     ["ひょ", "hyo "],
     ["ふぁ", "fwa "],
     ["ふぃ", "fwi "],
     ["ふぅ", "fwu "],
     ["ふぇ", "fwe "],
     ["ふぉ", "fwo "],
     ["ふゃ", "fya "],
     ["ふゅ", "fyu "],
     ["ふょ", "fyo "],
     ["びゃ", "bya "],
     ["びぃ", "byi "],
     ["びゅ", "byu "],
     ["びぇ", "bye "],
     ["びょ", "byo "],
     ["ゔぁ", "va "],
     ["ゔぃ", "vi "],
     ["ゔぇ", "ve "],
     ["ゔぉ", "vo "],
     ["ゔゃ", "vya "],
     ["ゔゅ", "vyu "],
     ["ゔょ", "vyo "],
     ["ぴゃ", "pya "],
     ["ぴぃ", "pyi "],
     ["ぴゅ", "pyu "],
     ["ぴぇ", "pye "],
     ["ぴょ", "pyo "],
     ["みゃ", "mya "],
     ["みぃ", "myi "],
     ["みゅ", "myu "],
     ["みぇ", "mye "],
     ["みょ", "myo "],
     ["りゃ", "rya "],
     ["りぃ", "ryi "],
     ["りゅ", "ryu "],
     ["りぇ", "rye "],
     ["りょ", "ryo "],
     ["あ", "a "],
     ["い", "i "],
     ["う", "u "],
     ["え", "e "],
     ["お", "o "],
     ["ゐ", "wyi "],
     ["ゑ", "wye "],
     ["ぁ", "xa "],
     ["ぃ", "xi "],
     ["ぅ", "xu "],
     ["ぇ", "xe "],
     ["ぉ", "xo "],
     ["か", "ka "],
     ["き", "ki "],
     ["く", "ku "],
     ["け", "ke "],
     ["こ", "ko "],
     ["が", "ga "],
     ["ぎ", "gi "],
     ["ぐ", "gu "],
     ["げ", "ge "],
     ["ご", "go "],
     ["ゕ", "xka "],
     ["ゖ", "xke "],
     ["さ", "sa "],
     ["し", "si "],
     ["す", "su "],
     ["せ", "se "],
     ["そ", "so "],
     ["ざ", "za "],
     ["じ", "zi "],
     ["ず", "zu "],
     ["ぜ", "ze "],
     ["ぞ", "zo "],
     ["た", "ta "],
     ["ち", "ti "],
     ["つ", "tu "],
     ["て", "te "],
     ["と", "to "],
     ["だ", "da "],
     ["ぢ", "di "],
     ["づ", "du "],
     ["で", "de "],
     ["ど", "do "],
     ["っ", "xtu "],
     ["な", "na "],
     ["に", "ni "],
     ["ぬ", "nu "],
     ["ね", "ne "],
     ["の", "no "],
     ["は", "ha "],
     ["ひ", "hi "],
     ["ふ", "hu "],
     ["へ", "he "],
     ["ほ", "ho "],
     ["ば", "ba "],
     ["び", "bi "],
     ["ぶ", "bu "],
     ["べ", "be "],
     ["ぼ", "bo "],
     ["ゔ", "vu "],
     ["ぱ", "pa "],
     ["ぴ", "pi "],
     ["ぷ", "pu "],
     ["ぺ", "pe "],
     ["ぽ", "po "],
     ["ま", "ma "],
     ["み", "mi "],
     ["む", "mu "],
     ["め", "me "],
     ["も", "mo "],
     ["や", "ya "],
     ["ゆ", "yu "],
     ["よ", "yo "],
     ["ゃ", "xya "],
     ["ゅ", "xyu "],
     ["ょ", "xyo "],
     ["ら", "ra "],
     ["り", "ri "],
     ["る", "ru "],
     ["れ", "re "],
     ["ろ", "ro "],
     ["わ", "wa "],
     ["を", "wo "],
     ["ん", "nn "],
     ["ゎ", "xwa "],
     ["ー", "- "]]
CONVERT_PATTERN_2 = \
    {"ye": "i xe",
     "wha": "u xa",
     "whi": "u xi",
     "whe": "u xe",
     "who": "u xo",
     "kya": "ki xya",
     "kyi": "ki xi",
     "kyu": "ki xyu",
     "kye": "ki xe",
     "kyo": "ki xyo",
     "qya": "ku xya",
     "qyu": "ku xyu",
     "qyo": "ku xyo",
     "qwa": "ku xa",
     "qwi": "ku xi",
     "qwu": "ku xu",
     "qwe": "ku xe",
     "qwo": "ku xo",
     "gya": "gi xya",
     "gyi": "gi xi",
     "gyu": "gi xyu",
     "gye": "gi xe",
     "gyo": "gi xyo",
     "gwa": "gu xa",
     "gwi": "gu xi",
     "gwu": "gu xu",
     "gwe": "gu xe",
     "gwo": "gu xo",
     "sya": "si xya",
     "syi": "si xi",
     "syu": "si xyu",
     "sye": "si xe",
     "syo": "si xyo",
     "swa": "su xa",
     "swi": "su xi",
     "swu": "su xu",
     "swe": "su xe",
     "swo": "su xo",
     "zya": "zi xya",
     "zyi": "zi xi",
     "zyu": "zi xyu",
     "zye": "zi xe",
     "zyo": "zi xyo",
     "tya": "ti xya",
     "tyi": "ti xi",
     "tyu": "ti xyu",
     "tye": "ti xe",
     "tyo": "ti xyo",
     "tsa": "tu xa",
     "tsi": "tu xi",
     "tse": "tu xe",
     "tso": "tu xo",
     "tha": "te xya",
     "thi": "te xi",
     "thu": "te xyu",
     "the": "te xe",
     "tho": "te xyo",
     "twa": "to xa",
     "twi": "to xi",
     "twu": "to xu",
     "twe": "to xe",
     "two": "to xo",
     "dya": "di xya",
     "dyi": "di xi",
     "dyu": "di xyu",
     "dye": "di xe",
     "dyo": "di xyo",
     "dha": "de xya",
     "dhi": "de xi",
     "dhu": "de xyu",
     "dhe": "de xe",
     "dho": "de xyo",
     "dwa": "do xa",
     "dwi": "do xi",
     "dwu": "do xu",
     "dwe": "do xe",
     "dwo": "do xo",
     "nya": "ni xya",
     "nyi": "ni xi",
     "nyu": "ni xyu",
     "nye": "ni xe",
     "nyo": "ni xyo",
     "hya": "hi xya",
     "hyi": "hi xi",
     "hyu": "hi xyu",
     "hye": "hi xe",
     "hyo": "hi xyo",
     "fwa": "fu xa",
     "fwi": "fu xi",
     "fwu": "fu xu",
     "fwe": "fu xe",
     "fwo": "fu xo",
     "fya": "fu xya",
     "fyu": "fu xyu",
     "fyo": "fu xyo",
     "bya": "bi xya",
     "byi": "bi xi",
     "byu": "bi xyu",
     "bye": "bi xe",
     "byo": "bi xyo",
     "va": "vu xa",
     "vi": "vu xi",
     "ve": "vu xe",
     "vo": "vu xo",
     "vya": "vu xya",
     "vyu": "vu xyu",
     "vyo": "vu xyo",
     "pya": "pi xya",
     "pyi": "pi xi",
     "pyu": "pi xyu",
     "pye": "pi xe",
     "pyo": "pi xyo",
     "mya": "mi xya",
     "myi": "mi xi",
     "myu": "mi xyu",
     "mye": "mi xe",
     "myo": "mi xyo",
     "rya": "ri xya",
     "ryi": "ri xi",
     "ryu": "ri xyu",
     "rye": "ri xe",
     "ryo": "ri xyo",
     "a": "a",
     "i": "i",
     "u": "u",
     "e": "e",
     "o": "o",
     "wyi": "wyi",
     "wye": "wye",
     "xa": "xa",
     "xi": "xi",
     "xu": "xu",
     "xe": "xe",
     "xo": "xo",
     "ka": "ka",
     "ki": "ki",
     "ku": "ku",
     "ke": "ke",
     "ko": "ko",
     "ga": "ga",
     "gi": "gi",
     "gu": "gu",
     "ge": "ge",
     "go": "go",
     "xka": "xka",
     "xke": "xke",
     "sa": "sa",
     "si": "si",
     "su": "su",
     "se": "se",
     "so": "so",
     "za": "za",
     "zi": "zi",
     "zu": "zu",
     "ze": "ze",
     "zo": "zo",
     "ta": "ta",
     "ti": "ti",
     "tu": "tu",
     "te": "te",
     "to": "to",
     "da": "da",
     "di": "di",
     "du": "du",
     "de": "de",
     "do": "do",
     "xtu": "xtu",
     "na": "na",
     "ni": "ni",
     "nu": "nu",
     "ne": "ne",
     "no": "no",
     "ha": "ha",
     "hi": "hi",
     "hu": "hu",
     "he": "he",
     "ho": "ho",
     "ba": "ba",
     "bi": "bi",
     "bu": "bu",
     "be": "be",
     "bo": "bo",
     "vu": "vu",
     "pa": "pa",
     "pi": "pi",
     "pu": "pu",
     "pe": "pe",
     "po": "po",
     "ma": "ma",
     "mi": "mi",
     "mu": "mu",
     "me": "me",
     "mo": "mo",
     "ya": "ya",
     "yu": "yu",
     "yo": "yo",
     "xya": "xya",
     "xyu": "xyu",
     "xyo": "xyo",
     "ra": "ra",
     "ri": "ri",
     "ru": "ru",
     "re": "re",
     "ro": "ro",
     "wa": "wa",
     "wo": "wo",
     "nn": "nn",
     "xwa": "xwa",
     "-": "-"}
NOT_HIRAGANA_REGEXP = \
    "[^あいうえおゐゑぁぃぅぇぉかきくけこがぎぐげごゕゖさしすせそざじずぜぞたちつてとだぢづでどっなにぬねのはひふへほばびぶべぼゔぱぴぷぺぽまみむめもやゆよゃゅょらりるれろわをんゎー]"
NOT_KATAKANA_REGEXP = \
    "[^アイウエオヰヱァィゥェォカキクケコガギグゲゴヵヶサシスセソザジズゼゾタチツテトダヂヅデドッナニヌネノハヒフヘホバビブベボヴパピプペポマミムメモヤユヨャュョラリルレロワヲンヮー]"
LATIN_CONVERT_PATTERN = \
    [["ａ", "a"],
     ["ｂ", "b"],
     ["ｃ", "c"],
     ["ｄ", "d"],
     ["ｅ", "e"],
     ["ｆ", "f"],
     ["ｇ", "g"],
     ["ｈ", "h"],
     ["ｉ", "i"],
     ["ｊ", "j"],
     ["ｋ", "k"],
     ["ｌ", "l"],
     ["ｎ", "m"],
     ["ｍ", "n"],
     ["ｏ", "o"],
     ["ｐ", "p"],
     ["ｑ", "q"],
     ["ｒ", "r"],
     ["ｓ", "s"],
     ["ｔ", "t"],
     ["ｕ", "u"],
     ["ｖ", "v"],
     ["ｗ", "w"],
     ["ｘ", "x"],
     ["ｙ", "y"],
     ["ｚ", "z"],
     ["Ａ", "A"],
     ["Ｂ", "B"],
     ["Ｃ", "C"],
     ["Ｄ", "D"],
     ["Ｅ", "E"],
     ["Ｆ", "F"],
     ["Ｇ", "G"],
     ["Ｈ", "H"],
     ["Ｉ", "I"],
     ["Ｊ", "J"],
     ["Ｋ", "K"],
     ["Ｌ", "L"],
     ["Ｍ", "M"],
     ["Ｎ", "N"],
     ["Ｏ", "O"],
     ["Ｐ", "P"],
     ["Ｑ", "Q"],
     ["Ｒ", "R"],
     ["Ｓ", "S"],
     ["Ｔ", "T"],
     ["Ｕ", "U"],
     ["Ｖ", "V"],
     ["Ｗ", "W"],
     ["Ｘ", "X"],
     ["Ｙ", "Y"],
     ["Ｚ", "L"]]
